#!/usr/bin/env ruby

require 'json'
require 'csv'
require 'pp'

# Translate old teams to their modern representation
TEAMS = {
  NOK: 'OKC',
  SEA: 'OKC',
  NOJ: 'UTA',
  BAL: 'WAS',
  CHP: 'WAS',
  CHZ: 'WAS',
  WSB: 'WAS',
  CAP: 'WAS',
  BUF: 'LAC',
  SDC: 'LAC',
  MLH: 'ATL',
  STL: 'ATL',
  TRI: 'ATL',
  VAN: 'MEM',
  ROC: 'SAC',
  KCK: 'SAC',
  KCO: 'SAC',
  CIN: 'SAC',
  SDR: 'HOU',
  CHO: 'CHA',
  CHH: 'CHA',
  PHW: 'GSW',
  SFW: 'GSW',
  SYR: 'PHI',
  MNL: 'LAL',
  FTW: 'DET',
  NYN: 'BKN',
  NJN: 'BKN',
  BRK: 'BKN',
  NOH: 'NOP',
  PHO: 'PHX'
}

# Teams that are no longer around
DEFUNCT = ['SHE', 'WAT', 'STB', 'WSC', 'AND', 'DNN', 'CHS', 'BLB', 'INO']

rows = CSV.read("coaches.csv",
  headers: true,
  header_converters: :symbol,
  converters: :numeric)

rows.each do |r|
  abbr = r[:team].to_sym
  r[:team] = TEAMS.has_key?(abbr) ? TEAMS[abbr] : abbr.to_s
end

rows.each do |row|
  row[:start] = row[:season].split('-').first.to_i
  row[:finish] = row[:start] + 1
end

rows = rows.select do |t|
  !DEFUNCT.include?(t[:team]) && t[:start] >= 1970
end

# teams = rows.select { |r| r[:team] == 'MIN' }
teams = rows.group_by {|r| r[:team] }

# Group coaches by tenures
teams = teams.map do |name, coaches|
  coaches.map!(&:to_h).sort_by! { |c| [c[:name], c[:season]] }

  coaching_stints = coaches.each_with_object([]) do |coach, stints|
    last_stint = stints.last
    if [coach[:name], coach[:start]] == last_stint&.fetch_values(:coach, :finish)
      last_stint[:finish] = coach[:finish]
      last_stint[:years].push(coach.delete_if {|c| [:name, :team].include?(c)})
    else
      stints << {
        coach: coach[:name],
        start: coach[:start],
        finish: coach[:finish],
        years: [coach.delete_if {|c| [:name, :team].include?(c)}]
      }
    end
  end
  [name, coaching_stints.sort_by { |c| [c[:start], c[:finish]] }]
end

puts JSON.pretty_generate(teams)
